FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ ./
ARG REACT_APP_BACKEND_URL=http://localhost:8080/api
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
RUN npm run build

FROM nginxinc/nginx-unprivileged
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
