version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vc-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  frontend:
    build:
      context: ./VictoryCenter-Client
      dockerfile: ../Dockerfile.frontend.local
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8080/api}
    container_name: vc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./VictoryCenter-Back
      dockerfile: Dockerfile
      args:
        Configuration: debug
    container_name: vc-backend
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/wwwroot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
      JWTOPTIONS_SECRETKEY: ${JWTOPTIONS_SECRETKEY}
      JWTOPTIONS_REFRESH_TOKEN_SECRETKEY: ${JWTOPTIONS_REFRESH_TOKEN_SECRETKEY}
      BLOB_LOCAL_STORE_KEY: ${BLOB_LOCAL_STORE_KEY}
      WAY4PAY_MERCHANT_LOGIN: ${WAY4PAY_MERCHANT_LOGIN}
      WAY4PAY_MERCHANT_SECRET_KEY: ${WAY4PAY_MERCHANT_SECRET_KEY}
      WAY4PAY_MERCHANT_DOMAIN_NAME: ${WAY4PAY_MERCHANT_DOMAIN_NAME}
      CLOUDFLARE_TURNSTILE_SECRET_KEY: ${CLOUDFLARE_TURNSTILE_SECRET_KEY}
      CLOUDFLARE_TURNSTILE_SITE_VERIFY_URL: ${CLOUDFLARE_TURNSTILE_SITE_VERIFY_URL}
      CONTACT_US_EMAIL_OPTIONS_FROM_ADDRESS: ${CONTACT_US_EMAIL_OPTIONS_FROM_ADDRESS}
      ContactUsEmailOptions__FromAddress: ${CONTACT_US_EMAIL_FROM_ADDRESS}
      CloudflareTurnstileCaptchaOptions__SecretKey: ${CLOUDFLARE_TURNSTILE_SECRET_KEY}
      CloudflareTurnstileCaptchaOptions__SiteVerifyUrl: ${CLOUDFLARE_TURNSTILE_SITE_VERIFY_URL}
      RESEND_API_TOKEN: ${RESEND_API_TOKEN}
      WAY4PAY_API_URL: ${WAY4PAY_API_URL}
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    depends_on:
      - sqlserver

volumes:
  sql_data:
